- docs/getting-started/getting-started.md
- docs/using-radicle/creating-and-sharing-projects.md
- docs/using-radicle/pushing-and-pulling-changes.md
Closes: https://github.com/radicle-dev/radicle-docs/issues/3.
> Improve using Radicle doc sections

- docs/radicle.md
Edits focused on differences with centralized forges.
Closes #10
> changes on radicle vs centralized forges

- docs/understanding-radicle/glossary.md
Due to the leading `/` the links could not be resolved and clicking on the links lead to an error page
> Fix internal links

- docs/getting-started.md
> Add supported platforms & fix-ups

- docs/radicle.md
- docs/understanding-radicle/faq.md
- docs/understanding-radicle/why-radicle.md
Mainly edits on centralized forges vs. Radicle and some small things here and there
> radicle vs forges and more edits

- docs/getting-started.md
Review of Getting Started
Closes #60
> Edits to Getting Started Page

- docs/using-radicle/adding-a-seed-node.md
- docs/using-radicle/contributing.md
- docs/using-radicle/creating-projects.md
- docs/using-radicle/fetching-and-merging.md
- docs/using-radicle/overview.md
- docs/using-radicle/pushing-changes.md
- docs/using-radicle/running-a-seed-node.md
- docs/using-radicle/sharing-projects.md
- docs/using-radicle/tracking-and-viewing.md
There are some edits using-radicle/overview as well.
Closes #54
> Edits to Using Radicle sections

- docs/using-radicle/overview.md
> Edits to Using-Radicle/Overview

- website/static/index.html
This should make the twitter card work.
> Twitter card

- docs/understanding-radicle/faq.md
- docs/using-radicle/fetching-and-merging.md
- docs/using-radicle/tracking-and-viewing.md
- docs/using-radicle/troubleshooting.md
@xla - can you jump in and write some quick answers for the three open questions at the bottom?
> Edits to FAQ page

- docs/getting-started.md
- docs/radicle.md
- docs/understanding-radicle/glossary.md
- docs/using-radicle/adding-a-seed-node.md
- docs/using-radicle/contributing.md
- docs/using-radicle/creating-projects.md
- docs/using-radicle/fetching-and-merging.md
- docs/using-radicle/overview.md
- docs/using-radicle/pushing-changes.md
Removed extraneous Radicle's and fixed some typos
> Cleanups 🧹

- docs/getting-started.md
- docs/understanding-radicle/faq.md
- docs/using-radicle/community.md
- docs/using-radicle/overview.md
- website/sidebars.json
Added a Join our Community section for info on our community channels.
> Added community section

- docs/understanding-radicle/faq.md
> faq: Add outstanding questions

- website/static/css/custom.css
> Fix styling for mobile

- docs/understanding-radicle/how-it-works.md
> Fix broken link in How it Works

- docs/using-radicle/contributing.md
- docs/using-radicle/creating-projects.md
- docs/using-radicle/fetching-and-merging.md
Notes based on user feedback in Matrix channel.
> Added note on publishing branches & communicating patches

- docs/using-radicle/community.md
> Add homeserver address to community page

- docs/understanding-radicle/how-it-works.md
Just saw this note I left for Fintan haha
> Quick typo fix to How it Works

- docs/understanding-radicle/why-radicle.md
Add missing link to Kim's post on IPFS.
closes #86
> add link to IPFS GitHub explanation

- docs/understanding-radicle/faq.md
> FAQ: add section for project deletion

- docs/understanding-radicle/glossary.md
- docs/using-radicle/overview.md
Replaces a dead link to link essay with a pointer to the how it works
section about seeding.
> Fix dead link to link

- docs/using-radicle/troubleshooting.md
After telling my story on #general I was asked to
> t'd be cool if you were able to add this to the FAQ or Troubleshooting section on our docs https://github.com/radicle-dev/radicle-docs/
> Add section about SSH_ASKPASS

- docs/get-involved/community.md
- docs/getting-started.md
- docs/radicle.md
- docs/using-radicle/overview.md
Closes #110 
Signed-off-by: abbey titcomb <abbeytitcomb@gmail.com>
> edited ethereum content & fixed links in blockquotes

- docs/using-radicle/adding-a-seed-node.md
- docs/using-radicle/running-a-seed-node.md
Added language on seed nodes and linked the radicle.community thread. Closes #115 
Signed-off-by: abbey titcomb <abbeytitcomb@gmail.com>
> add list of public seed nodes & disclaimer

- docs/using-radicle/running-a-seed-node.md
> Add seed node upgrade instructions

- docs/understanding-radicle/faq.md
- docs/using-radicle/fetching-and-merging.md
- docs/using-radicle/overview.md
```
[WARN] unresolved links in file 'understanding-radicle/faq.md' > [ 'using-radicle/community.md' ]
[WARN] unresolved links in file 'using-radicle/fetching-and-merging.md' > [ 'using-radicle/troubleshooting.md' ]
[WARN] unresolved links in file 'using-radicle/overview.md' > [ 'using-radicle/community.md' ]
```
Signed-off-by: Julien Donck <hello@juliendonck.com>
> Fix dead links

- docs/using-radicle/running-a-seed-node.md
> text reminder to restart terminal

- README.md
> Provide more information about signing commits

- docs/using-radicle/running-a-seed-node.md
Address some recurring questions from chat regarding seed connections, rewards and crashing.
> Address some issues raised in chat

- docs/connecting-to-ethereum/obtaining-rad.md
- docs/connecting-to-ethereum/overview.md
Address the common chat question about how to obtain the token.
> Add a page about sources for the RAD token

- docs/connecting-to-ethereum/overview.md
- website/sidebars.json
> Show Obtaining Rad page with a sidebar

- docs/using-radicle/running-a-seed-node.md
- Added a small addition in the documentation
> Updated running a seed node doc

- docs/getting-started.md
- docs/radicle.md
- docs/using-radicle/overview.md
- docs/versions.md
- website/package.json
- website/pages/en/versions.js
> Add NixOS package to docs and clean up language around supported macOS versions

- docs/understanding-radicle/how-it-works.md
"Degree" is the number of neighbours of a particular node, it doesn't make sense to say "n degrees out"
> "Degrees out" -> "hops out"

- README.md
Just being more clear how to publish updates to the docs.
> change USER to USERNAME in README

- docs/connecting-to-ethereum/obtaining-rad.md
Signed-off-by: Julien Donck <hello@juliendonck.com>
> add binance to obtaining rad page

- docs/getting-started.md
Signed-off-by: Miss M <MissM_signed@protonmail.ch>
Fixes #173
Fixes #174
> Fix install instructions

- docs/get-involved/obtain-rad.md
- sidebars.js
> Re-add the doc on obtaining RAD

- docs/using-radicle/identity.md
- sidebars.js
We've had some questions around managing Radicle identities, plus a recently-merged but undocumented way to delete identities, so this doc is a start in the right direction.
> New doc: Manage your Radicle identity

- docusaurus.config.js
- package.json
- sidebars.js
- yarn.lock
Self-explanatory—just staying on top of the latest.
> Update docusaurus to 2.1.0

- docs/using-radicle/issues.md
See small change
Feel free to merge if good
> Typo - Issue usage

- docs/understanding-radicle/faq.md
> Fix: typos

- README.md
Plus, removed one more mention of "user-centric" docs.
> Change Radicle -> RadicleDAO in main README

- docs/governance/transition-dao.md
Updated referring to Orgs and CDO - STILL NEED TO CHANGE DAO NAME ONCE CONFIRMED
> Change text in Transition to the DAO page

- docs/community/04_faq.md
- docs/community/06_stay-up-to-date.md
- src/components/Grid.module.css
- src/css/custom.css
- src/theme/DocItem/Footer/styles.module.css
Fixed some issues around how custom components show up in dark mode. Also increasing the heading font size a little bit throughout, and fixed some heading depth issues in a few of the docs.
> Styling updates for launch

- docs/community/02_our_story.md
- package.json
- src/components/Timeline.js
- src/components/Timeline.module.css
- yarn.lock
Came up with a better way to style the [timeline](https://docs.radworks.org/community/our-story). The pro is that it looks nice, but the con is that I'm using a custom component for it—something else to maintain, potentially, and adding items isn't as intuitive as writing in pure Markdown. An entry looks like this:
```
<Timeline
date="September, 2017"
title="The [oscoin manifesto](https://web.archive.org/web/20170912030149/http://oscoin.io/) goes live"
desc="The initial mission & vision of the project are released out in the wild."
/>
```
The con might not be _that_ bad, because we should only be adding new items fairly infrequently, I would guess. But if this is a no-go, I can try another solution.
Screenshot of the new version:
> Implement timeline in a component for better styling

- docs/community/01_ecosystem.md
- docs/community/02_our_story.md
- docs/community/03_governance_overview.md
- docs/community/04_faq.md
- docs/community/06_stay-up-to-date.md
- docs/community/README.md
- sidebars.js
- src/theme/DocItem/Footer/index.js
- src/theme/DocItem/Footer/styles.module.css
- fixed headers
- updated copy
> final docs site edits

- docs/community/01_ecosystem.md
> fixed ecosystem diagrams

- package.json
- yarn.lock
Not upgrading for any specific features, but just to stay on track with development so we don't get left behind and have to deal with a big migration later when we _do_ want new features.
https://github.com/facebook/docusaurus/releases/tag/v2.3.1
> Update Docusaurus to 2.3.1

- docs/community/01_ecosystem.md
The points I wanted to get across:
- Distinction/relationship of Radicle Foundation & Foundation Org
- Org work funded via treasury
- Foundation (entity) has limited power, focused on maintaining real world requirements for Radworks
> clarifications to Radicle Foundation/Org

- sidebars.js
change to github link until more stable version of Radicle is released.
> update manual link

- docs/community/01_ecosystem.md
> update ecosystem overview image

- docs/community/README.md
- add note that we operate as a community-governed network that uses both off and onchain governance to make decisions.
> Update Introduction page

- docs/community/03_governance_overview.md
I think it is important to make the distinction clearer between how onchain and offchain governance is used.
> make clearer what governance is used for at RW

- docs/community/README.md
Update "What is Radworks" definition based on Ele feedback Remove "our" language based on Ange feedback
> update "What is Radworks" definition, remove "our" language

- docs/community/02_our_story.md
Add:
- RadicleDAO > Radworks 
- Drips V2 launch (wording needs work)
- Radworks funds critical dependancies via drips
> update recent history

- docs/community/01_ecosystem.md
- add RIT Org
- align wording linking to 2024 proposals
> add Radicle Integrations & Tooling Org

- docs/community/03_governance_overview.md
- add links to main voting platforms
- create clearer sections
- add delegation info
- make "ways to participate" in gov clearer
Still need to add images once finalized
> WIP: Restructure Gov Overview page
