better-internet/radworks-docs

- docs/getting-started.md
Had to do a quick fix to edit the link to the binary in the onboarding email I'm sending this weekend
> Fixed binary link for onboarding email

- docs/understanding-radicle/faq.md
In the FAQ, the link to seed info for the final question wasn't displayed on the website.
If you need to rebase, feel free to delete my PR and correct the typo yourself.
> Typo: change [si[ to [si]

- docs/using-radicle/running-a-seed-node.md
The docs weren't explicit enough, which led to some confusion.
Signed-off-by: Rūdolfs Ošiņš <rudolfs@osins.org>
> Update seed docs

- website/siteConfig.js
Algolia finally got back to us. They configured an indexer for us on their free-tier, it runs every 24h. If we need changes to it we should open a PR at: https://github.com/algolia/docsearch-configs/blob/master/configs/radicle.json.
Closes: #46
> Add search config

- docs/getting-started.md
This is to avoid having to make pull requests in two repositories when doing a release. We'll have to update the links
only in the radicle.xyz repository from now on.
> Link to radicle.xyz download page instead of deep-link

- docs/radicle.md
Fixes #113
If HTML anchors are used the `.md` suffix is not stripped from the link.
> Fix link to “Undestanding Radicle”

- docs/using-radicle/running-a-seed-node.md
Some people in chatroom didn't realise that seed.my.org is not an example domain. Use something more obvious - may as well follow RFC2606
> Use a more obvious example URL

- docs/understanding-radicle/faq.md
Add instructions on how to register the `radicle://` custom protocol on Linux.
⚠️ We should merge this only after https://github.com/radicle-dev/radicle-upstream/pull/1652 is publicly released.
> Add a section in the FAQ about deep linking

- docs/using-radicle/running-a-seed-node.md
This fixes a tiny typo I've found on the seed node instructions page. @abbey-titcomb could you please have a look?
> Fixes typo on seed node page

- website/core/Footer.js
- website/siteConfig.js
- website/static/css/custom.css
Remove obsolete license headers and copyright information. The license headers in these files were left overs from the original code. This code has been removed so the license does not apply anymore.
Fixes #162
> remove obsolete license headers

- docs/get-involved/community.md
- docs/getting-started.md
- docs/radicle.md
- docs/understanding-radicle/faq.md
- docs/understanding-radicle/glossary.md
- docs/understanding-radicle/how-it-works.md
- docs/understanding-radicle/troubleshooting.md
This PR follows up on #165 to remove a few extra references to Upstream from the FAQ, glossary, and troubleshooting docs. It also adds few new definitions for things like Seed IDs and project URNs.
> Remove additional Upstream references

- docs/understanding-radicle/glossary.md
This just points to existing docs really and simply highlights the importance of "monorepo" as a term in the Radicle domain.
cc @joelhans @abbey-titcomb (as per contributing docs)
> Add monorepo term

- docs/getting-started.md
Docs should recommend installing the version of the rad client the documentation is made for.
Many users are installing the latest unstable version for which the docs are incompatible with.
> getting-started: lock rad-cli client to docs

- docs/getting-started.md
This PR removes the CLI and Upstream installation instructions and instead points to [radicle.xyz](https://radicle.xyz/get-started.html) for canonical instructions. This should help clarify the process and remove any discrepancies between them.
> Remove install instructions and point to radicle.xyz

- .github/workflows/deploy.yml
When combined with the deploy preview I added in #192, this should automate all deployments to docs.radicle.xyz.
> Migrate to deploying via GitHub Actions

- docs/get-involved/community.md
- docs/getting-started.md
- docs/migrate-github-radicle.mdx
- docs/radicle.md
- sidebars.js
- src/components/Highlight.js
- src/components/Installation.js
As the title suggest, this guide covers the bare minimum steps one needs to migrate from GitHub—basically, run `rad init` and `rad push`—and then help point them to other docs that flesh out their understanding of the Radicle experience.
Obviously, the content isn't dramatically different from our main [install instructions](https://radicle.xyz/get-started.html), but I think it's important to provide some context and simplify the leap from GitHub to Radicle.
> Add guide: Migrate from GitHub to Radicle

- docs/migrate-github-radicle.mdx
During the UX studies we've been running with new users, we noticed that the seed node selection actually confuses people. It was common to be met with reactions like "if all 3 seed nodes are run by radicle, why pick one over the others?". 
This will hopefully make it clearer.
> Reduce confusion around seed node selection

- docs/troubleshooting.md
I've realized we can probably group `ssh-agent`-related issues into one section. The errors might be different, but the solution is the same. I also added a tabbed code block for macOS/Linux instructions.
> Tweak troubleshooting based on recent Discord chats

- docs/understanding-radicle/radicle-versus-github-gitlab.md
- sidebars.js
This PR expands on the comparison featured on the homepage and provides some additional/richer context for those who are interested. I think it's important to vigorously defend Radicle's choices around sovereignty but also provide transparency into areas where Radicle's features are not 100% on par with GitHub or GitLab.
> New doc: Radicle versus GitHub and GitLab

- src/components/Grid.js
- src/components/Grid.module.css
Based on a comment I left on #243, I changed the `<Grid>` component to automatically add an icon if the URL points to an external site. Here's an example of what that looks like:
> Add external link icon to grid boxes

- docusaurus.config.js
- src/css/custom.css
- src/theme/DocItem/Footer/index.js
- src/theme/DocItem/Footer/styles.module.css
In the Figma designs for the new docs structure, @shelbeeee requested we build a box that goes at the bottom of every doc with some helpful links. The new structure is being worked on, but I ended up taking a swing at implementing the box itself.
A screenshot of the current implementation:
The `Last updated...` and `Edit this page` sections can't really be changed, but all other design/copy/links are customizable—I figure I'll update those once the new structure is merged.
> Create 'info box' beneath docs content
